name = "quiet-spots-api"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "quiet-spots-db"
database_id = "b0dcc856-89cd-4a63-9f80-39243f752c12"
migrations_dir = "migrations"
